version: "3.8"

services:
    web:
        image: "folio-backend:dev"

        build:
            target: development_build
            context: .
            cache_from:
                - "folio-backend:dev"
                - "folio-backend:latest"
                - "*"
            args:
                DJANGO_ENV: development
        command: python -Wd manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db

    db:
        image: postgres:12.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.dev

volumes:
    postgres_data:
